blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/serhatkildaci/global-car-models/discussions
    about: Ask questions and discuss ideas with the community
