name: Sync Data Files

on:
  push:
    branches:
      - main
    paths:
      - 'data/models.json'
      - 'data/models.csv'
      - 'data/models.yaml'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          data/models.json
          data/models.csv
          data/models.yaml

    - name: Set up Python
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      run: pip install pyyaml

    - name: Determine trigger file and sync data
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
        echo "Changed files: $changed_files"
        
        # Find the first data file that was changed
        if [[ "$changed_files" == *"data/models.json"* ]]; then
          export TRIGGER_FILE="data/models.json"
        elif [[ "$changed_files" == *"data/models.csv"* ]]; then
          export TRIGGER_FILE="data/models.csv"
        elif [[ "$changed_files" == *"data/models.yaml"* ]]; then
          export TRIGGER_FILE="data/models.yaml"
        else
          export TRIGGER_FILE="data/models.json"
        fi
        
        echo "Using trigger file: $TRIGGER_FILE"
        python scripts/sync_data.py

    - name: Commit and push changes
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: auto-sync data files"
        file_pattern: "data/models.json data/models.csv data/models.yaml"
